### ISSUE TITLE
No registry publishers shown

### ISSUE THREAD

**Issue by dalepotter** [IATI/AidInfoLabs-CSV-Downloader#2]
The [public instance](http://tools.aidinfolabs.org/csv/direct_from_registry/) of the CSV Conversion Tool is currently displaying 'Loading' in the box which presumably should show the list of publishers from the Registry.

![image](https://cloud.githubusercontent.com/assets/8247168/20705695/deebdd3e-b61b-11e6-997a-a06603acba5f.png)

**Comment by hayfield** [comment]
This is occurring due to a CORS rule.

**Comment by hayfield** [comment]
Is it desired that this issue is fixed in the interim until the tool is shut down since it causes intended functionality not to work? @dalepotter

**Comment by nosvalds** [comment]
Tool has been deprecated.
