### ISSUE TITLE
Migrate Functionality to Python Library

### ISSUE THREAD

**Issue by hayfield** [IATI/AidInfoLabs-CSV-Downloader#3]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), the AidInfoLabs CSV Downloader is to be shut down. Before this occurs, the functionality of converting IATI XML to CSV should be ported to the Python Library.

**Comment by nosvalds** [comment]
See https://cdn.iatistandard.org/prod-iati-website/documents/CSV_Conversion_Deprecation_Guide.pdf
