### ISSUE TITLE
Shut down AidInfoLabs CSV Downloader

### ISSUE THREAD

**Issue by hayfield** [IATI/AidInfoLabs-CSV-Downloader#4]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), the AidInfoLabs CSV Downloader is to be shut down.

This is blocked by #3

**Comment by nosvalds** [comment]
- https://cdn.iatistandard.org/prod-iati-website/documents/CSV_Conversion_Deprecation_Guide.pdf
- https://iatistandard.org/en/news/removal-of-iati-previewer-and-csv-conversion-tool/
