### ISSUE TITLE
Transaction Type displaying dates instead of transaction types

### ISSUE THREAD

**Issue by PetyaKangalova** [IATI/AidInfoLabs-CSV-Downloader#5]
I have been notified by a user that the AidInfoLabs- CSV-Downloader  is showing the incorrect information in the Transaction Type field. The specific file where this issue has occurred is UNICEF Madagascar: https://iatiregistry.org/dataset/unicef-madagascar. I have used the all transactions (CSV) download option. I can confirm that transaction type has been specified in the data. However, in the CSV file, column N, Transaction Type displays **the dates** instead of the transaction type (see screenshot below).

![image](https://user-images.githubusercontent.com/24607542/28266234-ab115504-6aeb-11e7-8c89-bd701f4b0260.png)

I have managed to download the data via the IATI Datastore and share with the user, but it will be useful to understand whether this is a bug with the tool. Would you be able to look into this and let me know?

Many thanks!

**Comment by dalepotter** [comment]
This does appear to be a bug with the tool. We've added this to the list of maintenance jobs for next week and it will be looked at this next Monday. We will post a further update then.

**Comment by allthatilk** [comment]
This issue should now be fixed. The template was set up improperly for the 'all transactions' selection so it wasn't generating the columns in the right order or grabbing the transaction codes. Have made the appropriate changes.

**Comment by PetyaKangalova** [comment]
@allthatilk  thanks very much! I have also just checked and can now see that the transaction type has been identified correctly in the CSV file. I'll inform the user now and close this issue.
